version: 2
jobs:
  build_and_test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      # restore folders with npm dependencies and Cypress binary
      - restore_cache:
          keys:
            - cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # install npm dependencies and Cypress binary
      # if they were cached, this step is super quick
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm run cy:verify
      # save npm dependencies and Cypress binary for future runs
      - save_cache:
          key: cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      
      - run:
          name: Static analysis
          command: npm run ci:lint
            
      - run:
          name: Build client
          command: npm run build

      # start the server, would prefer to use closer-to-production env but `now dev` isnt quite there
      - run:
          name: Start servers
          command: npm run start:dev
          background: true

      - run:
          name: Check server is ready
          command: npm run ci:ping-server

      - run:
          name: Run integration tests
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build_and_test